apiVersion: v1
kind: Service
metadata:
  name: greencompute-control-plane
spec:
  selector:
    app: greencompute-control-plane
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000

