apiVersion: v1
kind: ConfigMap
metadata:
  name: greencompute-observability
data:
  dashboards.yaml: |
    dashboards:
      - greencompute-control-plane
      - greencompute-validator
      - greencompute-miner

